# Generated by Django 6.1 on 2026-09-03 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_type', models.CharField(choices=[('INQUIRY', '問い合わせ'), ('SHOWING_REQUEST', '内覧希望'), ('PURCHASE_INTENT', '購入申込'), ('PRICE_NEGOTIATION', '価格交渉')], default='INQUIRY', max_length=20)),
                ('inquiry_date', models.DateTimeField(auto_now_add=True)),
                ('inquiry_text', models.TextField(blank=True)),
                ('target_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='customers.customer')),
                ('target_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='properties.property')),
            ],
        ),
    ]
