# Generated by Django 6.1 on 2026-09-03 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contract_date', models.DateField()),
                ('handover_date', models.DateField()),
                ('status', models.CharField(choices=[('PREPARING', '契約前'), ('SIGNED', '契約締結'), ('REVIEWING', 'ローン審査'), ('COMPLETED', '決済・引渡'), ('CANCELED', 'キャンセル・破談')], default='PREPARING', max_length=20)),
                ('target_accounts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to=settings.AUTH_USER_MODEL)),
                ('target_customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='customers.customer')),
                ('target_property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='properties.property')),
            ],
        ),
    ]
