# Generated by Django 6.1 on 2026-08-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', '管理者'), ('EDITOR', '編集者'), ('VIEWER', '閲覧者')], default='VIEWER', max_length=10),
        ),
    ]
