# Generated by Django 6.1 on 2026-09-03 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('town', models.CharField(db_index=True, max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=12)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('property_type', models.CharField(choices=[('LAND', '土地'), ('BUILDING', '建物'), ('COND', 'マンション')], db_index=True, default='LAND', max_length=10)),
                ('property_status', models.CharField(choices=[('AVAILABLE', '公開中'), ('PENDING', '商談中'), ('SOLD', '売約済み'), ('HIDDEN', '非公開')], db_index=True, default='AVAILABLE', max_length=10)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='properties.property')),
                ('area', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('building_structure', models.CharField(choices=[('WOOD', '木造'), ('S', '鉄骨造'), ('RC', '鉄筋コンクリート造'), ('SRC', '鉄骨鉄筋コンクリート造'), ('OTHER', 'その他')], db_index=True, default='WOOD', max_length=20)),
                ('build_year', models.IntegerField(blank=True, null=True, verbose_name='築年（西暦）')),
                ('build_month', models.IntegerField(blank=True, null=True, verbose_name='築月')),
                ('floor_plan', models.CharField(blank=True, max_length=20)),
                ('road_access', models.CharField(blank=True, max_length=20)),
            ],
            bases=('properties.property',),
        ),
        migrations.CreateModel(
            name='Cond',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='properties.property')),
                ('area', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('condominium_name', models.CharField(max_length=100)),
                ('room_number', models.CharField(max_length=20)),
                ('floor', models.IntegerField()),
                ('management_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('maintenance_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pet_policy', models.CharField(choices=[('ALLOWED', '可'), ('NOT_ALLOWED', '不可'), ('NEGOTIABLE', '要相談')], db_index=True, default='NOT_ALLOWED', max_length=20)),
                ('management_type', models.CharField(choices=[('SELF_MANAGED', '自主管理'), ('CONTRACTED', '委託管理'), ('OTHER', 'その他')], default='CONTRACTED', max_length=20)),
            ],
            bases=('properties.property',),
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='properties.property')),
                ('area', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('building_coverage_ratio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('floor_area_ratio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('land_category', models.CharField(choices=[('RESIDENTIAL', '宅地'), ('AGRICULTURAL', '農地'), ('FOREST', '山林'), ('OTHER', 'その他')], default='RESIDENTIAL', max_length=20)),
                ('land_right_type', models.CharField(choices=[('OWNERSHIP', '所有権'), ('LEASEHOLD', '借地権'), ('OTHER', 'その他')], default='OWNERSHIP', max_length=20)),
            ],
            bases=('properties.property',),
        ),
    ]
